/**
 * Bus status constants
 */
const BUS_STATUS = {
    AVAILABLE: 'AVAILABLE',
    RUNNING: 'RUNNING',
    REST: 'REST',
    MAINTENANCE: 'MAINTENANCE',
};

/**
 * Driver status constants
 */
const DRIVER_STATUS = {
    AVAILABLE: 'AVAILABLE',
    RUNNING: 'RUNNING',
    OFF_DUTY: 'OFF_DUTY',
};

/**
 * Route status constants
 */
const ROUTE_STATUS = {
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
};

/**
 * Activity action types
 */
const ACTIVITY_ACTIONS = {
    // Bus actions
    BUS_STATUS_CHANGE: 'BUS_STATUS_CHANGE',
    BUS_ASSIGNED_TO_ROUTE: 'BUS_ASSIGNED_TO_ROUTE',
    BUS_UNASSIGNED_FROM_ROUTE: 'BUS_UNASSIGNED_FROM_ROUTE',
    BUS_ROUND_COMPLETED: 'BUS_ROUND_COMPLETED',
    BUS_SENT_TO_REST: 'BUS_SENT_TO_REST',
    BUS_SENT_TO_MAINTENANCE: 'BUS_SENT_TO_MAINTENANCE',

    // Driver actions
    DRIVER_STATUS_CHANGE: 'DRIVER_STATUS_CHANGE',
    DRIVER_ASSIGNED_TO_ROUTE: 'DRIVER_ASSIGNED_TO_ROUTE',
    DRIVER_UNASSIGNED_FROM_ROUTE: 'DRIVER_UNASSIGNED_FROM_ROUTE',
    DRIVER_WENT_OFF_DUTY: 'DRIVER_WENT_OFF_DUTY',

    // Route actions
    ROUTE_ASSIGNMENT_CREATED: 'ROUTE_ASSIGNMENT_CREATED',
    ROUTE_ASSIGNMENT_UPDATED: 'ROUTE_ASSIGNMENT_UPDATED',
    ROUTE_ASSIGNMENT_ENDED: 'ROUTE_ASSIGNMENT_ENDED',
    ROUTE_COMPLETED: 'ROUTE_COMPLETED',
    ROUTE_REACTIVATED: 'ROUTE_REACTIVATED',

    // Admin actions
    ADMIN_FORCE_ASSIGN_BUS: 'ADMIN_FORCE_ASSIGN_BUS',
    ADMIN_FORCE_ASSIGN_DRIVER: 'ADMIN_FORCE_ASSIGN_DRIVER',
};

/**
 * Socket event names
 */
const SOCKET_EVENTS = {
    BUS_STATUS_CHANGE: 'bus:statusChange',
    DRIVER_STATUS_CHANGE: 'driver:statusChange',
    ROUTE_ASSIGNMENT_CHANGE: 'route:assignmentChange',
    ADMIN_FORCE_ASSIGNMENT: 'admin:forceAssignment',
    DASHBOARD_REFRESH: 'dashboard:refresh',
    CRON_EXECUTED: 'cron:executed',
};

module.exports = {
    BUS_STATUS,
    DRIVER_STATUS,
    ROUTE_STATUS,
    ACTIVITY_ACTIONS,
    SOCKET_EVENTS,
};
